controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']
api_login_check:
    path: /api/login_check
